### ISSUE TITLE
Trying to use steem from browser

### ISSUE THREAD

**Issue by Netherdrake** [adcpm/steem#39]
I am trying to use `steem` in a Meteor app.

I've installed steem via npm, here are my dependencies:
```
  "dependencies": {
    "babel-runtime": "^6.18.0",
    "bcrypt": "^0.8.7",
    "bufferutil": "^1.2.1",
    "crypto": "0.0.3",
    "crypto-browserify": "^3.11.0",
    "meteor-node-stubs": "^0.2.3",
    "steem": "^0.3.30",
    "utf-8-validate": "^1.2.1"
  }
```

However when I try to import steem, I get the following error:
```
import steem from 'steem';
```

Output:
![](https://i.gyazo.com/11dc81507d2de88798e7cba74b3fb67d.png)

If I try to import the script from CDN, it fails to sign things:
https://cdn.steemjs.com/lib/latest/steem.min.js

Code:
```
steem.broadcast.vote(wif, voter, author, permlink, weight, function(err, result) {
    console.log(err, result);
});
```

Output:
```
Error: 3030008 tx_missing_posting_auth: missing required posting authority(…) undefined
```

Interestingly enough, this same code works fine when ran from node.js.

**Comment by p0o** [comment]
I see the error is related to your `crypto` module rather than steem. Please try following commands and check if it's fixed or not:

```
rm -rf node_modules
npm cache clean
npm i
```

**Comment by Netherdrake** [comment]
Unfortunately, reinstalling node_modules did not solve the problem.

It might be a problem with Meteor.

**Comment by Netherdrake** [comment]
Ok, I found the solution in [second comment here](https://github.com/meteor/meteor/issues/2050)

Looks like on of the dependencies is installing crap version of `crypto`.

**Comment by Netherdrake** [comment]
Unfortunately however, I still can't get it to sign anything correctly:
```
    steem.broadcast.vote(wif, username, author, permlink, 10000, function(err, result) {
        console.log(err, result);
    });
```

```
Error: 3030008 tx_missing_posting_auth: missing required posting authority(…) undefined
```

**Comment by adcpm** [comment]
I've tried to replicate the code and test it on browser and it was working. I'm uploaded the code used here https://github.com/adcpm/steem/blob/dev/examples/broadcast.html maybe you can test it. Are you sure that you are using a posting wif? Do you use the min.js from GitHub latest version? Strange if it work on server-side it should work same way on browser.

**Comment by adcpm** [comment]
Here is the code to reproduce the error: https://github.com/Netherdrake/meteor-test It's working on browser but when steem.js is compiled by meteor the broadcast of a vote fail.

**Comment by Netherdrake** [comment]
Furthermore, installing `steem` breaks the whole Meteor app in the first place, as it installs a bad `crypto` package:
https://github.com/adcpm/steemauth/blob/dev/package.json#L30

Im not sure if the two issues have any correlation.

**Comment by p0o** [comment]
I replicated the error. To me it seems like it's an error related to different packages of `crypto` one on `steemauth` package and another [the built-in crypto package](https://nodejs.org/api/crypto.html) of the node. Seems running the app on meteor forces steemauth to use the built-in package and it's not giving the same output as the one from npm module. In the other hand, installing steem installs the npm package of crypto which is breaking your Meteor app since it's installing a different package.

I'm not familiar much with steemauth package but I think if the crypto package get removed from it and the steemauth uses the built-in crypto of node (and get tested if it works correctly), the issue should be resolved.

**Comment by nil1511** [comment]
While compiling webpack convert `crypto` module to `crypto-browserify`.
`crypto-browserify` is working fine in browser and must be having issue with meteor. 

Meteor is generating different [hash (https://github.com/adcpm/steemauth/blob/dev/lib/protocol/signature/hash.js#L16) which  result in different signature in broadcast.

You can manually try using `steem/dist/steem.min.js`. running as https://github.com/Netherdrake/meteor-test/blob/8b730de8cc2ababaabb5c4cf40a4cd10877a40f6/imports/browser-test.html.

**Comment by Netherdrake** [comment]
If I remove `steem` from node modules, and use https://cdn.steemjs.com/lib/latest/steem.min.js instead, I still get the same error in a Meteor app.

**Comment by nil1511** [comment]
@Netherdrake yes and using same js without meteor works.

**Comment by Netherdrake** [comment]
Correct. Do you have any ideas why that is?

**Comment by Netherdrake** [comment]
My observations lead to the same conclusion. The library only malfunctions when used in Meteor.

I have created a new, cleaner repo with two versions, Meteor and non-meteor, supporting the case.
https://github.com/Netherdrake/steem-meteor-test

**Comment by nil1511** [comment]
with meteor return [hash](https://github.com/adcpm/steemauth/blob/dev/lib/protocol/signature/hash.js#L16) does not work properly. different value with and without meteor for same input.

**Comment by p0o** [comment]
Could it be possibly the reason?

>crypto.createHash(algorithm)
The algorithm is dependent on the available algorithms supported by the version of OpenSSL on the platform. Examples are 'sha256', 'sha512', etc.

[Source](https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm)

**Comment by Netherdrake** [comment]
I get the exact same output from node as I do from Meteor app on:

```
let test = crypto.createHash('sha256').update("foo").digest()
```

```
<Buffer 2c 26 b4 6b 68 ff c6 8f f9 9b 45 3c 1d 30 41 34 13 42 2d 70 64 83 bf a0 f9 8a 5e 88 62 66 e7 ae>
```

**Comment by nil1511** [comment]
Try removing es5-shim from your meteor app. `meteor remove es5-shim` 

new Date('2016-11-27T13:17:20').getTime() is different in meteor app. because the time zone is not specified.

**Comment by Netherdrake** [comment]
Woohoo, it works :)

**Comment by nkgokul** [comment]
I am trying to use SteemTestnet from browser and am facing the exact same issue. You can check the HTML page on https://nkgokul.github.io/steem-tutorials/SteemTestnetPost.html and the code for the same on https://github.com/nkgokul/steem-tutorials/blob/master/SteemTestnetPost.html

![screen shot 2018-04-18 at 11 38 24 am](https://user-images.githubusercontent.com/1375897/38917573-d337b3fc-4308-11e8-9fbb-39e1f0f3468d.png)

**Comment by BartolomeoItaliano** [comment]
It looks like you are passing wrong posting private key

**Comment by nkgokul** [comment]
I thought so too and verified the creds are current. Since it is a test account I am sharing the creds which you can verify. 

username : steemtest
posting WIF : 5J8fxGuPkSU5UFYWk2yeFkzAGhYSnYZpTQ95dHQLGosiajUnisy

I logged in with these credentials and posted a new entry which you can check on https://condenser.steem.vc/test/@steemtest/testing-it-with-posting-wif

You can login yourself on https://condenser.steem.vc with above credentials. 

I also tried to post with the same code and different creds on the steem mainnet just to be sure that there was no problem with the code. I was able to do that as well. 

So the only difference has to be from this code

```javascript
    if (development) {
      steem.api.setOptions({ url: 'https://testnet.steem.vc' });
      steem.api.setOptions({ address_prefix: 'STX' });
      steem.api.setOptions({ chain_id: '79276aea5d4877d9a25892eaa01b0adf019d3e5cb12a97478df3298ccdd01673' });
      ACCOUNT_NAME = 'steemtest'
      ACCOUNT_WIF = '5J8fxGuPkSU5UFYWk2yeFkzAGhYSnYZpTQ95dHQLGosiajUnisy' //private
    }else{
      steem.api.setOptions({ url: 'https://api.steemit.com' });
      ACCOUNT_NAME = 'vergetips'
      ACCOUNT_WIF = 'posting WIF of vergetips'
    }
```
